site_name: 'bioimageio.core'
site_url: 'https://bioimage-io.github.io/core-bioimage-io-python'
site_author: Fynn Beuttenmüller
site_description: 'Python specific core utilities for bioimage.io resources (in particular DL models).'

repo_name: bioimage-io/core-bioimage-io-python
repo_url: https://github.com/bioimage-io/core-bioimage-io-python
edit_uri: edit/main/docs/

theme:
  name: material
  language: en
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.preview
    - navigation.instant.progress
    - navigation.path
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate

  palette:
    - media: '(prefers-color-scheme)'
      primary: 'deep-purple'
      accent: 'blue'
      toggle:
        icon: material/brightness-auto
        name: 'Switch to light mode'
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: 'deep-purple'
      accent: 'blue'
      toggle:
        icon: material/brightness-7
        name: 'Switch to dark mode'
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: 'deep-purple'
      accent: 'blue'
      toggle:
        icon: material/brightness-4
        name: 'Switch to system preference'

  font:
    text: Roboto
    code: Roboto Mono

  logo: images/bioimage-io-icon.png
  favicon: images/favicon.ico

plugins:
  - autorefs
  - coverage:
      html_report_dir: dist/coverage
  - markdown-exec
  - mkdocstrings:
      enable_inventory: true
      default_handler: python
      locale: en
      handlers:
        python:
          inventories:
            - https://docs.pydantic.dev/latest/objects.inv
            - https://bioimage-io.github.io/spec-bioimage-io/latest/objects.inv
            - https://bioimage-io.github.io/spec-bioimage-io/dev/objects.inv
          options:
            annotations_path: source
            backlinks: tree
            docstring_options:
              ignore_init_summary: true
              returns_multiple_items: false
              returns_named_value: false
              trim_doctest_flags: true
            docstring_section_style: spacy
            docstring_style: google
            filters: ['!^_[^_]']
            heading_level: 1
            imported_members: false
            inherited_members: true
            members: true
            merge_init_into_class: true
            parameter_headings: true
            preload_modules: [pydantic, bioimageio.spec]
            scoped_crossrefs: true
            separate_signature: true
            show_docstring_examples: true
            show_if_no_docstring: true
            show_inheritance_diagram: true
            show_root_full_path: false
            show_root_heading: true
            show_signature_annotations: true
            show_source: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true
            summary: true
            # unwrap_annotated: true
            extensions:
              - griffe_pydantic:
                  schema: true
              - griffe_inherited_docstrings
              - griffe_public_redundant_aliases
  - mike:
      alias_type: symlink
      canonical_version: latest
      version_selector: true
  - gen-files:
      scripts:
        - scripts/generate_api_doc_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - search
  - section-index

markdown_extensions:
  - attr_list
  - admonition
  - callouts:
      strip_period: false
  - footnotes
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      pygments_lang_class: true
  - pymdownx.magiclink
  - pymdownx.snippets:
      base_path: [!relative $config_dir]
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: '¤'
      permalink_title: Anchor link to this section for reference
      toc_depth: 2

nav:
  - Home:
      - index.md
      - Compatibility: compatibility.md
  - API Reference: reference/
  - Changelog: changelog.md
  - Coverage report: coverage.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/bioimage-io
  version:
    provider: mike
