name: bio-core-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - black
  - bioimageio.spec
  - conda-build
  - h5py >=2.10,<2.11
  - mypy
  - pytest
  - python >=3.7
  - xarray
  - pytorch
  - onnxruntime
  - tensorflow >=1.12,<2.0
