name: bio-core-torch
channels:
  - conda-forge
  - defaults
dependencies:
  - bioimageio.spec==0.5.*
  - black
  - conda-build
  - filelock
  - h5py
  - loguru
  - mypy
  - onnx
  - onnxruntime
  - pip
  - psutil
  - pytest
  - pytest-xdist
  - python >=3.7
  - pytorch
  - ruyaml
  - tifffile <=2022.4.8 # pin fixes Syntax error; see https://github.com/bioimage-io/core-bioimage-io-python/pull/259
  - typer
  - xarray
