name: bio-core-tf
channels:
  - conda-forge
  - defaults
dependencies:
  - black
  - bioimageio.spec
  - conda-build
  - h5py >=2.10,<2.11
  - mypy
  - pip
  - pytest
  - python >=3.7,<3.8  # this environment is only available for python 3.7
  - xarray
  - tensorflow >=1.12,<2.0
  - tifffile
  - pip:
    - keras==1.2.2
