name: bio-core-torch
channels:
  - conda-forge
  - defaults
dependencies:
  - black
  - bioimageio.spec >=0.4.4
  - conda-build
  - h5py
  - mypy
  - pip
  - pytest
  - python >=3.7
  - xarray
  - pytorch
  - onnxruntime
  - tifffile <=2022.4.8  # pin fixes Syntax error; see https://github.com/bioimage-io/core-bioimage-io-python/pull/259

