name: bio-core-dev
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - black
  - bioimageio.spec
  - conda-build
  - mypy
  - pytest
  - python >=3.7
  - pytorch
  - cpuonly
  - onnxruntime
  - tensorflow
